# http://travis-ci.org/#!/mozilla/configman
language: python

python:
    - 2.6
    - 2.7

before_install:
    - pip install -r test-requirements.txt

install:
    - python setup.py install

script:
    - nosetests configman

notifications:
    irc:
        channels: "irc.mozilla.org#breakpad"

deploy:
    provider: pypi
    user: peterbe
    password:
        secure: pLLUb5KUKlK+/G05WxbWhv0TCBqtsdgK6FylIca1EkfvVeVSEZzbL/ptSKt47cIUypm6tkbcG2QE1FzCD/Oj/JnttJyQg0UMOFnobbYqaldgDYi6LXNejG4/5SqNkMu0yabkcK0nKx2s614lCAUypvWZrX5KYh61vHT/+Asxqek=
    on:
        tags: true
        repo: mozilla/configman
        branch: travis-ci-deployment-by-tags
    distributions: "sdist bdist_wheel"
